using System.Net;
using wikimediatests.Models.API.Routes;
using wikimediatests.Tests.Fixtures;
using FluentAssertions;
using System.Text.Json;
using wikimediatests.Models.API.ResponseModels.Search.Pages;
using wikimediatests.Models.API.ResponseModels.Pages;

namespace wikimediatests.Tests.API
{
    public class Tests : TestsCoreFixtures
    {
        private SearchRoute SearchRoute;
        private static string QueryDefault = "furry rabbits";
        private SearchPageResultModel PagesFromSearchResult;

        [SetUp]
        public async Task Setup()
        {
            SearchRoute = new SearchRoute(requestContext: PlaywrightRequest);

            // WHEN - A search for pages containing for ‘furry rabbits’ is executed
            var requestResponse = await SearchRoute.GetSearchPageResult(query: QueryDefault);
            requestResponse.StatusText.Should().Be(HttpStatusCode.OK.ToString());

            var requestResponseBody = requestResponse.JsonAsync().Result;
            requestResponseBody.Should().NotBeNull();
            PagesFromSearchResult = requestResponseBody.Value.Deserialize<SearchPageResultModel>();
            PagesFromSearchResult.Should().NotBeNull();
        }

        [Test]
        [TestCase("Sesame Street")]
        public async Task PageWithTitleCanBeFound(string expectedPageToExist)
        {
            // THEN - A page with the title ‘Sesame Street’ is found
            var isContainingPage = PagesFromSearchResult.pages.Any(p => p.title.Equals(expectedPageToExist));
            isContainingPage.Should().BeTrue();
        }

        [Test]
        [TestCase("Sesame Street", "2023-08-17")]
        public async Task PageHasExpectedTimeStamp(string pageUnderTest, string expectedTimeStamp)
        {
            // GIVEN - The result for ‘furry rabbits’ search contains ‘Sesame Street’
            var pageSearchDetails = PagesFromSearchResult.pages.FirstOrDefault(p => p.title.Equals(pageUnderTest));
            pageSearchDetails.Should().NotBeNull();

            // WHEN - The page details for Sesame Street are requested
            var pageRoutes = new PagesRoute(requestContext: PlaywrightRequest);
            var pageRequestResponse = await pageRoutes.GetPage(page: pageSearchDetails);
            pageRequestResponse.StatusText.Should().Be(HttpStatusCode.OK.ToString());

            // THEN - It has a latest timestamp > 2023-08-17
            var requestResponseBody = pageRequestResponse.JsonAsync().Result;
            requestResponseBody.Should().NotBeNull();
            var pageDetails = requestResponseBody.Value.Deserialize<SinglePageDetails>();
            DateTime.TryParse(expectedTimeStamp, out var pageExpectedTime);
            pageDetails.latest.timestamp.Should().BeAfter(pageExpectedTime);
        }

        // Part 2. Additional scenarious. Request type: GET Route: /core/v1/{project}/{language}/page/{title}/bare
        // Scenario 3. Send GET request where page title is LOWER case to check end point case sensetive. Based on requirements;
        // Scenario 4. Send GET request where page title is UPPER case to check end point case sensetive. Based on requirements;
        // Scenario 5. Send GET request where page title has spaces instead of underscores. Example: use - 'Sesame Street' and not 'Sesame_Street'. Check how route handles spaces;
        // Scenario 6. Send GET request where page title is SQL query to check basic vulnerability protection;
        // Scenario 7. Send GET request where page title is unknown/not existed page to check if route returns '404 Not found' response code with body that page, with requested title, does not exist
        // Scenario 8. Send GET request where page title is title of the page that was deleted. to check if route returns '404 Not found' response code with body that page, with requested title, does not exist

        // Bonus. To create a page via that API, you need to provide an Authorization Header. Describe how you would
        // adapt testing/automation? Assume we just created that public Wikipedia API.Describe which other aspects you would want to
        // test and how.
        //
        // Describe how you would adapt testing/automation?
        // I would create new class something like 'ApiManager' where APIRequest is initiated.
        // 'ApiManager' must be injected into all objects from 'wikimediatests.Models.API.Routes' instead of 'IAPIRequestContext'. 
        // 'ApiManager' would have public method which allows to make requests.
        // To make a call public method requires to provide: route, request type, headers, params, and isAuthorize (which is bool). If isAuthorize is true - then send request with
        // auth token otherwise not. 
        //
        // Describe which other aspects you would want to test and how.
        // Funtional
            // 1. Token generation - can be generated by user 
            // 2. Token validation - can be used by end user to make request
            // 3. Token expiration/revokation - tokens can not be used
            // 4. automatic rotation - if there is this feature
            // 5. any resource is not available/reachable without token 
            // 6. if token is supposed to be used on front and back end. Perform integration testing.
            // 7. If it grands access to specific data/functionality/level only - check it as well.
            // 8. Check that use does not have access to data/functionality/level that was not granted
        //Non Functional
        // 1. Check if token is encrypted in storage
        // 2. check that if token has request rate limit
    }
}